### ISSUE TITLE
[Bug] Bug

### ISSUE THREAD

**Issue by PingClan** [JDiscordBots/Mee6-bypasser#17]
**Describe the bug**
The !rank Command doesnt give the members the role. Is there a new Version from the Mee6 Bypasser?

**Comment by danthe1st** [comment]
Can you please share all necessary detail? For example, please share your configuration (output of `mb!show`) and the role hierachy .

**Comment by danthe1st** [comment]
I will have a look at it.

**Comment by PingClan** [comment]
Pls can you fix it. I maked the roles and so.. but it doesnt give the Roles.

**Comment by danthe1st** [comment]
Does it work now?
If it does not, keep in mind the following aspects:
- The highest role of `Mee6-bypasser` (normally also named `Mee6-bypasser`) needs to be higher than the role to assign.
- Enter the command `mb!show` in order to display roles to assign. The role to assign needs to be included in order to work.

**Comment by w1llll** [comment]
yeah im having this issue too

**Comment by danthe1st** [comment]
I think this occurs if too many people execute `!rank` at the same time as Mee6 blocks Mee6-bypasser because of too many requests. It might work if you wait a minute and try again.
