### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xSimpLUL** [JDiscordBots/Mee6-bypasser#22]
Users aren't getting their roles when typing !rank. Bot has all perms and is above all other roles, and the role is configured properly with mee6 bypasser and leaderboards are public.

**Comment by danthe1st** [comment]
Mee6-bypasser has a rate limit that allows only one user per server to use it per minute.

This is in place so that Mee6-bypasser is not getting blocked from Mee6 because of sending too many requests.

If you want to remove this rate limit, clone the bot, remove it from the source code, build it and host Mee6-bypasser by yourself.
